# Gmail SMTP
spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: ecommstore98@gmail.com
    password: gygwkyoxctlkixrs
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
